### ISSUE TITLE
Compilation problem "ldr.h : No such file or directory"

### ISSUE THREAD

**Issue by jcgrenier** [xiangzhou/GEMMA#28]
Hello there,

I'm trying to compile GEMMA on my system. I changed my lapack libraries directory. So it should not be a problem with this. Here's what I get :

$ make
g++ -Wall -O3 -std=gnu++11 -DWITH_LAPACK -m64 -static  -c src/main.cpp -o src/main.o
g++ -Wall -O3 -std=gnu++11 -DWITH_LAPACK -m64 -static  -c src/param.cpp -o src/param.o
In file included from src/Eigen/Cholesky:24:0,
                 from src/Eigen/Dense:3,
                 from src/mathfunc.h:24,
                 from src/param.cpp:35:
src/Eigen/src/Cholesky/LDLT.h: In member function ‘void Eigen::internal::solve_retval<Eigen::LDLT<MatrixType, _UpLo>, Rhs>::evalTo(Dest&) const’:
src/Eigen/src/Cholesky/LDLT.h:505:39: attention : typedef ‘Scalar’ locally defined but not used [-Wunused-local-typedefs]
     typedef typename LDLTType::Scalar Scalar;
                                       ^
src/param.cpp: In member function ‘void PARAM::ReadFiles()’:
src/param.cpp:281:137: attention : ‘W’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   if (ReadFile_bed (file_str, setSnps, W, indicator_idv, indicator_snp, snpInfo, maf_level, miss_level, hwe_level, r2_level, ns_test_tmp)==false) {error=true;}
                                                                                                                                         ^
g++ -Wall -O3 -std=gnu++11 -DWITH_LAPACK -m64 -static  -c src/gemma.cpp -o src/gemma.o
src/gemma.cpp:54:17: erreur fatale: ldr.h : Aucun fichier ou dossier de ce type
 #include "ldr.h"
                 ^
compilation terminée.
make: **\* [src/gemma.o] Erreur 1

Sorry, the system is in french, but you see there that the error is coming from the fact that it's not finding the class file ldr.h.

Thanks for your help.

JC

**Comment by xiangzhou** [comment]
I updated gemma.cpp file. This should fix this issue.

**Comment by jcgrenier** [comment]
Thanks for this,

I'm getting another one that is not found now. "varcov.h" .

Thanks for helping us with this!

**Comment by xiangzhou** [comment]
How about now?

**Comment by jcgrenier** [comment]
Still not good. varcov.h is not found. It's not in the src directory and is still in the gemma.cpp file.

**Comment by xiangzhou** [comment]
I forgot to push gemma.cpp up last time. The new file should be on git now.

**Comment by jcgrenier** [comment]
Thanks, I'm trying to install all of this now!

**Comment by jcgrenier** [comment]
Seems like it fixed it! Thanks a lot!
